name: Build & Test Services

on:
  workflow_call:
    inputs:
      changed-services:
        required: true
        type: string

jobs:
  build-test:
    if: ${{ inputs.changed-services != '[]' && inputs.changed-services != '' }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        service: ${{ fromJson(inputs.changed-services) }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build & Test
        working-directory: app/${{ matrix.service }}
        run: |
          mvn -B clean test

      - name: Docker build & push (only PR → main)
        if: ${{ github.event_name == 'pull_request' && github.base_ref == 'main' }}
        working-directory: app/${{ matrix.service }}
        run: |
          IMAGE=ghcr.io/${{ github.repository_owner }}/${{ matrix.service }}:${GITHUB_SHA}
          docker build -t $IMAGE .
          echo ${{ secrets.GHCR_PAT }} | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
          docker push $IMAGE
