name: CI - Feature Branch

on:
  push:
    branches:
      - 'ft/*'

jobs:
  detect-changes:
    uses: ./.github/workflows/scan-changes.yml


  build-test:
    needs: detect-changes
    uses: ./.github/workflows/build-test.yml
    with:
      services: ${{ needs.detect-changes.outputs.changed-services }}

