name: Microservice CI/CD

on:
  push:
    branches:
      - 'ft/*'
  pull_request:
    branches:
      - main

jobs:
  detect-changes:
    uses: ./.github/workflows/detect-changes.yml


  build-test:
    needs: detect-changes
    uses: ./.github/workflows/build-and-test.yml
    with:
      changed-services: ${{ needs.detect-changes.outputs.changed-services }}
