name: CI Pipeline

on:
  push:
    branches:
      - dev
      - ft/*
  pull_request:
    branches:
      - dev
      - main

jobs:
  build:
    uses: ./.github/workflows/build-services.yml
    with:
      # For PRs to dev or main → full build
      run_full_build: ${{ github.event_name == 'pull_request' }}

