name: Detect Changed Services

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches:
      - dev
      - main

jobs:
  detect:
    runs-on: ubuntu-latest
    outputs:
      changed-services: ${{ steps.detect.outputs.services }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Detect changed services
        id: detect
        run: |
          CHANGED=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^app/' | cut -d/ -f2 | sort -u | tr '\n' ',' | sed 's/,$//')
          echo "Changed services: $CHANGED"
          echo "services=$CHANGED" >> $GITHUB_OUTPUT
